
export const AFTER_SALES_STATUS_PENDING = { text: '待处理', label: '待处理', value: 'PENDING', status: '售后中' }
export const AFTER_SALES_STATUS_OPERATION_PENDING = { text: '运营待审核', label: '运营待审核', value: 'OPERATION_PENDING', status: '售后中' }
export const AFTER_SALES_STATUS_REFUND_PENDING = { text: '财务待退款', label: '财务待退款', value: 'REFUND_PENDING', status: '售后中' }
export const AFTER_SALES_STATUS_REFUNDED = { text: '已退款', label: '已退款', value: 'REFUNDED', status: '已退款' }
export const AFTER_SALES_STATUS_APPLY_DISAGREE = { text: '拒绝申请', label: '拒绝申请', value: 'APPLY_DISAGREE', status: '售后完成' }
export const AFTER_SALES_STATUS_REFUND_DISAGREE = { text: '拒绝退款', label: '拒绝退款', value: 'REFUND_DISAGREE', status: '售后完成' }
export const AFTER_SALES_STATUS_WAREHOUSE_SEND_PENDING = { text: '库房待补寄', label: '库房待补寄', value: 'WAREHOUSE_SEND_PENDING', status: '售后中' }
export const AFTER_SALES_STATUS_WAREHOUSE_IN_STORE_PENDING = { text: '库房待入库', label: '库房待入库', value: 'WAREHOUSE_IN_STORE_PENDING', status: '售后中' }
export const AFTER_SALES_STATUS_MEMBER_SIGN_IN_PENDING = { text: '用户待签收', label: '用户待签收', value: 'MEMBER_SIGN_IN_PENDING', status: '售后完成' }
export const AFTER_SALES_STATUS_PRODUCT_RETURN_REFUSE = { text: '商品拒收', label: '商品拒收', value: 'PRODUCT_RETURN_REFUSE', status: '售后完成' }

export default [
  AFTER_SALES_STATUS_PENDING,
  AFTER_SALES_STATUS_OPERATION_PENDING,
  AFTER_SALES_STATUS_REFUND_PENDING,
  AFTER_SALES_STATUS_REFUNDED,
  AFTER_SALES_STATUS_APPLY_DISAGREE,
  AFTER_SALES_STATUS_REFUND_DISAGREE,
  AFTER_SALES_STATUS_WAREHOUSE_SEND_PENDING,
  AFTER_SALES_STATUS_WAREHOUSE_IN_STORE_PENDING,
  AFTER_SALES_STATUS_MEMBER_SIGN_IN_PENDING,
  AFTER_SALES_STATUS_PRODUCT_RETURN_REFUSE
]

export const AFTER_SALES_STATUS = {
  PENDING: AFTER_SALES_STATUS_PENDING,
  OPERATION_PENDING: AFTER_SALES_STATUS_OPERATION_PENDING,
  REFUND_PENDING: AFTER_SALES_STATUS_REFUND_PENDING,
  REFUNDED: AFTER_SALES_STATUS_REFUNDED,
  APPLY_DISAGREE: AFTER_SALES_STATUS_APPLY_DISAGREE,
  REFUND_DISAGREE: AFTER_SALES_STATUS_REFUND_DISAGREE,
  WAREHOUSE_SEND_PENDING: AFTER_SALES_STATUS_WAREHOUSE_SEND_PENDING,
  WAREHOUSE_IN_STORE_PENDING: AFTER_SALES_STATUS_WAREHOUSE_IN_STORE_PENDING,
  MEMBER_SIGN_IN_PENDING: AFTER_SALES_STATUS_MEMBER_SIGN_IN_PENDING,
  PRODUCT_RETURN_REFUSE: AFTER_SALES_STATUS_PRODUCT_RETURN_REFUSE
}
