export const ORDER_SET_ADDRESS = 'ORDER_SET_ADDRESS'
export const ORDER_REMOVE_ADDRESS = 'ORDER_REMOVE_ADDRESS'
export const ORDER_SET_HAS_ADDRESS = 'ORDER_SET_HAS_ADDRESS'

export const ORDER_SET_INVOICE = 'ORDER_GET_INVOICE'

export const ORDER_SET_INVOICE_TYPE = 'ORDER_SET_INVOICE_TYPE'


export const ORDER_SET_COUPON = 'ORDER_GET_COUPON'
export const ORDER_SET_NO_THRESHOLD_COUPON = 'ORDER_SET_NO_THRESHOLD_COUPON'

export const ORDER_SET_ID_CARD = 'ORDER_SET_ID_CARD'


export const ORDER_SET_COUPONDTOS = 'ORDER_GET_COUPONDTOS'
export const ORDER_SET_NOTHRESHOLDCOUPONDTOS = 'ORDER_GET_NOTHRESHOLDCOUPONDTOS'
export const ORDER_SET_COUPON_VISIBLE = 'ORDER_SET_COUPON_VISIBLE'
export const ORDER_SET_COUPON_SELECT = 'ORDER_SET_COUPON_SELECT'

export const ORDER_SET_CUSTOM_INFO = 'ORDER_SET_CUSTOM_INFO'

export const ORDER_SET_ALL_SKU_VISIBLE = 'ORDER_SET_ALL_SKU_VISIBLE'
